### ISSUE TITLE
Unable to save draft

### ISSUE THREAD

**Issue by sempasha** [elementary/mail#757]
### What Happened?

I'm unable to save draft with error:

```
Unable to save draft
There was an unexpected error while saving your draft.
Details: No such folder folder://local/Drafts
```
![Screenshot from 2022-01-18 11 46 45](https://user-images.githubusercontent.com/1610465/149885184-12f47f0b-69e1-4cba-9ea2-3156ae9163da.png

### Steps to Reproduce

1. Press *Compose new message* button;
2. Enter target address and subject;
3. Try to close *New Message* window.

### Expected Behavior

Draft to be saved.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Application provides no debug logs at moment of fail.
```

### Hardware Info

Quad-Core Intel® Core™ i7-8565U CPU @ 1.80GHz
Intel® UHD Graphics 620 (Whiskey Lake)
15.3 GiB memory
498.7 GB storage

**Comment by marbetschar** [comment]
@sempasha in order to help I do have to more questions: does the draft folder in the folder listing has a special icon - or is it just a regular, generic folder icon? Which email provider are you using? 

Asking because the special folder action such as "Save to draft" or "Archiving" depend on the correct auto-detection of such folders during account configuration in Online Accounts. A special icon indicates this detection went as expected - if its just a generic folder icon then something went wrong here.

**Comment by marbetschar** [comment]
@sempasha yeah, I figured. That´s not how it should look like :)

But it should work since https://github.com/elementary/mail/issues/620 was fixed. Have you ever tried to delete and re-add the account through Online Accounts?

**Comment by sempasha** [comment]
This is recently added account, my system installation is only few days old.
In my case remove/add account has no effect, error is still here.

**Comment by marbetschar** [comment]
I'm not able to reproduce. It works on my end once I configured the account as described here (if "Allow insecure apps" is enabled): https://support.google.com/mail/answer/7126229?hl=en

Any idea whats different on your end?

**Comment by sempasha** [comment]
No idea. I'll back to this issue later.
